### PR TITLE
Dev star

### LINKED ISSUE #36: use star to get an overview of latest releases in all repositories
Created PR:

https://github.com/tooomm/github-release-stats/pull/35

Cheers

### PR DESCRIPTION
**Pull request by mann1x**
Fixes #36

Added use star for overview all latest releases

### CODE REVIEW

**Comment by tooomm** [comment]
Can you please give more details and describe your changes in the start comment briefly?
You put everything in a big commit, that's a bit confusing to follow and track down.
I see you included other changes as well.

Quick notes again:
- It looks like the sorting still doesn't work correctly
- The last main release is still not shown, only the pre-release

When trying the old version out, I rate limited myself because of the amount of additional API calls that needs to fire to get all this information from all repos and their releases I guess. 🙈 
This seems to not happen now when quickly trying. Did you change something that could have caused this?
rate

That would not be good... There are many orgs that are bigger or users with many repos, it would be very bad if we kill the app when trying to get data from them.

<br>

I carried the communication from the former PR (#35) over:

>>This is an interesting idea, I see some issues though...
Who do you think is this useful for? In which scenario would somebody need such an overview on an org level?
>>
>Overview of downloads for all the latest releases, guess is something everyone is doing :P

Hehe, sure. People like statistics and want to learn about users and orgs.
Not so sure if this is the right tool for such a task though.

>When you issue a new release you wonder if it's being picked up.

One just needs to check the stats for that repo. No need to check the org overview for information on a single release. :P

**Comment by mann1x** [comment]
> Can you please give more details and describe your changes in the start comment briefly?
> You put everything in a big commit, that's a bit confusing to follow and track down.
> I see you included other changes as well.

I will describe it better sure.
Except the fix for the 0 downloads coming out as undefined there's only the * support for the overview.
Which other changes do you see?
It's a big commit cause I had to make a lot of changes to support it.
Sorry I'm a Sunday's developer :)

> Quick notes again:
> 
> * It looks like the sorting still doesn't work correctly

Sorting is based on updated_at, there's no info on the repo about the latest release (or if there's any sadly)

> * The last main release is still not shown (it shows the last pre-release for me)

This is odd the pre_release and draft should be filtered out, can you give me an example?

Maybe I got it wrong:

`    data.filter(function(a, b) {
        return b.draft == false && b.prerelease == false;
    });
`

> When trying the old version out, I rate limited myself because of the amount of additional API calls that needs to fire to get all this information from all repos and their releases I guess. 🙈
> This seems to not happen now when quickly trying. Did you change something that could have caused this?
> That would not be good... There are many orgs that are bigger or users with many repos, it would be very bad if we kill the app when trying to get data from them.

Not really, not sure why...
Thought 5000/hr was a lot but it's only 1,4/s calls.
Anyway after a bit of struggling I've added a throttling of the API calls.
But it's pretty slow even with very few repos.
I'll check if I can introduce a progress in percentage.

> Hehe, sure. People like statistics and want to learn about users and orgs.
> Not so sure if this is the right tool for such a task though.

For me makes sense for small developers.
Orgs will probably have much better and paid for tools.

> One just needs to check the stats for that repo. No need to check the org overview for information on a single release. :P

You think about orgs, I think about developers :)
Few repos with few releases, for me means saving a couple of browser tabs.
Everything that can reduce the amount of open tabs is welcome to me :P

**Comment by mann1x** [comment]
I don't like as well the ordering, I will change how it works.
I'm also going to use the API call with latest which will filter already the draft and pre-release.

Where do you want the better description, in the PR comment or in the commit description?

**Comment by mann1x** [comment]
Made way too many changes, I'll have to maintain it in my own fork...

**Pull request closed without merging**
