### PR TITLE
Added use star for overview all latest releases

### PR DESCRIPTION
**Pull request by mann1x**

### CODE REVIEW

**Comment by tooomm** [comment]
Some quick notes:
- The new repo overview with the various releases is not ordered by date. I guess that makes more sense?
- There are only newest releases listed, no matter if it's a pre-release or "full" release.
If a project delivers e.g. beta releases as pre-release, then their probably more important main release is not shown and counted at all.

This is an interesting idea, I see some issues though...
Who do you think is this useful for? In which scenario would somebody need such an overview on an org level?

**Comment by mann1x** [comment]
Yes, you are right should be ordered and I didn't think about the pre-releases.

There were some issues I've found as well about error handling and another issue with releases without downloads (I think this is also on the master).

Overview of downloads for all the latest releases, guess is something everyone is doing :P
When you issue a new release you wonder if it's being picked up.

**Comment by tooomm** [comment]
>There were some issues I've found as well about error handling and another issue with releases without downloads (I think this is also on the master).

If they are unrelated to this change, it's probably better to handle them in their own branch.
Do you recall the issues?

I only know that releases with no downloads show `undefined`, see #21 and #8

**Comment by mann1x** [comment]
Yes it was the undefined, I will make a new PR

**Pull request closed without merging**
